version: 0.2.{build}

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\AppData\Local\electron-builder\Cache'
  # - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 x64
  - npm install
  - git reset --hard HEAD
  - node --version

build_script:
  - npm run build

test: off

artifacts:
  # pushing all .exe files in build directory
  - path: 'build\*.exe'

deploy:
  release: '$(APPVEYOR_REPO_TAG_NAME)'
  description: '> $(APPVEYOR_REPO_TAG_NAME) => AppVeyor Build Version: $(APPVEYOR_BUILD_VERSION)'
  provider: GitHub
  draft: true
  prerelease: false
  force_update: true
  artifact: /.*\.exe/
  auth_token:
    secure: 6cDgNnnyJGzsudb0jDPnpGTXyhjKqmHhMGaoOvcluqcRahBUW0jr+lJGfTU4nT1Z
  on:
    branch: master # release from master branch only
    APPVEYOR_REPO_TAG: true # deploy on tag push only
